@echo off
echo Starting MPLADS Development Servers...

REM Start Backend
echo Starting Backend...
start "MPLADS Backend" cmd /k "cd backend && call venv\Scripts\activate.bat && python -m uvicorn app.main:app --reload --port 8000"

REM Start Frontend
echo Starting Frontend...
start "MPLADS Frontend" cmd /k "npm run dev"

echo Both servers are starting...
echo Waiting a few seconds before opening the browser...
timeout /t 3 /nobreak > nul
start http://localhost:5173
